server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver

linkConversion:
  linkSettings:
    serverUrl: http://localhost:${server.port}/
    linkLength: 7

